### ISSUE TITLE
Add the ability to tell the internet speed to user

### ISSUE THREAD

**Issue by sakshichahal53** [Anna-Assistant/Anna#175]
Till now, Anna just opens up a new tab when asked to show internet speed for the inputs:
Hey,
![56942472_1977998612323418_153891714757558272_n](https://user-images.githubusercontent.com/25123590/56223477-74ee3680-608b-11e9-9de8-45a8040ae67c.png)

We'd like to add web scraping to fast.com and help Anna know the speed so as to speak to the user.

**Comment by sakshichahal53** [comment]
Hey @gauthamzz, I am having difficulty implementing scraping in javascript. You could assign it to someone else who wants to work on it for now.

**Comment by gauthamzz** [comment]
Sure, Can you update the docs for internet speed feature.

**Comment by sakshichahal53** [comment]
Okay, on it.

**Comment by gundeeps22** [comment]
Hi, 

So I don't know if you guys have figured this out, but since you haven't closed the issue yet I am assuming this is still something you guys are working on. I figured out how to scrape dynamic websites, in particular fast.com. From the website I can obtain the internet speed. The problem is that the program is coded in Python. After reading online, you can integrate python code with js using a simple post request to the file. I have uploaded the python code to obtain the internet speed. I am also linking the stackoverflow post discussing how to integrate python code with js (https://stackoverflow.com/questions/13175510/call-python-function-from-javascript-code). 

Let me know what you guys think. 

CODE:
# code modified from https://stackoverflow.com/questions/42147601/pyqt4-to-pyqt5-mainframe-deprecated-need-fix-to-load-web-pages


import bs4 as bs
import sys
import time
import urllib.request
from PyQt5.QtWebEngineWidgets import QWebEnginePage
from PyQt5.QtWidgets import QApplication
from PyQt5.QtCore import QUrl

class Page(QWebEnginePage):
    def __init__(self, url):
        self.app = QApplication(sys.argv)
        QWebEnginePage.__init__(self)
        self.html = ''
        self.loadFinished.connect(self._on_load_finished)
        self.load(QUrl(url))
        self.app.exec_()

    def _on_load_finished(self):
        time.sleep(20)
        self.html = self.toHtml(self.Callable)

    def Callable(self, html_str):
        self.html = html_str
        self.app.quit()


def main():
    page = Page('https://fast.com/')
    # source = urllib.request.urlopen("https://fast.com/")
    soup = bs.BeautifulSoup(page.html, 'html.parser')
    js_test = soup.find("div", {"class": "speed-results-container"})
    print (js_test.contents[0])

if __name__ == '__main__': main()

**Comment by sakshichahal53** [comment]
Hi @gundeeps22, we too were actually thinking to use a python script for the code which could be integrated using API calls. However, it would be great to find a JS code for the same. However, we'd surely look up for the above help. Thank you so much.

**Comment by gauthamzz** [comment]
Can't you try something like get the name of the div and then just speak its value using JS

**Comment by gundeeps22** [comment]
@gauthamzz We cannot do this because the website fast.com is dynamic meaning it will not have the proper value when we get the html. As a result, to get the appropriate data in the field we must run the JS code on the website much like a browser does, which is where the python code comes in.

**Comment by gundeeps22** [comment]
@sakshichahal53 So from what I understand, there are JS counterparts of the libraries used in the python; however, those libraries require npm packages to be downloaded. This would require one of two things. Either we include those packages in our project, or we run a script that downloads the npm packages on each system using the extension.

**Comment by gauthamzz** [comment]
I think we can drop this feature for now then, i don't want to add python and js in the codebase. 

I think we need to start a server then.
