### ISSUE TITLE
Add "What is this" feature

### ISSUE THREAD

**Issue by gauthamzz** [Anna-Assistant/Anna#30]
If an image is the browser . Anna will reverse image search what that image is using google and tell the user what that is. 

Comment before doing this issue and discuss how you will solve it.

**Comment by gauthamzz** [comment]
intent name : reversesearch
user says: "whats on the page?" "what is this?" "whats on the screen?" "reverse search"

**Comment by sanketgautam** [comment]
Hey, After going through several possibilities, I have a plan for implementation of this feature,

1. We can use Chrome Extensions API to take screenshot of the current/active tab. (it has already been done in the Screenshot Feature, we can use that method)

2. Then we can upload the screenshot file to file.io using it's HTTP API
     -  It has a limit of 100 requests per day & for a free plan doesn't require any API Key
     -  but, this is the best I could find (this is for the initial POC, we can later replace that with some more robust & complex APIs like Dropbox, Amazon S3, Google Drive etc.)
3. then we can use the following url to open the new tab, using Chrome's Extension API, to show results to the user,
    - https://www.google.com/searchbyimage?&imageurl=https://file.io/[generated_ID]
    -  this will open google reverse image search page

Please let me know, if any changes required in proposed approach and assign me this issue, so that I can start working on this feature.

**Comment by gauthamzz** [comment]
assigned to @skg234
